########################
# Global Config
########################

#cache:
#    key: "$CI_RUNNER_ID"
#    paths:
#        - dl/

variables:
    CI_BR2_DL_DIR: "buildroot-ci/dl"
    GIT_STRATEGY: none

before_script:
    - export CI_BR2_DL_DIR=$HOME/$CI_BR2_DL_DIR
    - export

########################
# Job Templates
########################

# Global job template
# Used by all jobs
.global_job_template: &global_job_template
    only:
        - /.*-ci$/
        - next
        - master
        - triggers
        - tags

# Global build job template
# Used by all build jobs
.build_job_template: &build_job_template
    <<: *global_job_template  
    stage: build
    script:
        - ./build.py --dl $CI_BR2_DL_DIR/$CI_JOB_PLATFORM -u -b $CI_JOB_BOARD -p $CI_JOB_PLATFORM --ccache -q -l logs/${CI_BUILD_NAME}.log
    artifacts:
        paths:
            - output/$CI_JOB_BOARD*/images/$CI_JOB_BOARD*.zip
            - output/$CI_JOB_BOARD*/images/$CI_JOB_BOARD*.gz
        expire_in: 1 month

########################
# Pipeline Definition
########################

stages:
    - prep
    - sources_common
    - sources_custom
    - build
    - upload_logs

########################
# Jobs
########################

# Download the sources for all supported platforms
# Perform the download for one platform first, then copy the common bits
# To the others to save time
common_sources_job:
    <<: *global_job_template  
    stage: sources_common
    variables:
        GIT_STRATEGY: fetch
    script:
        - echo "Preparing Common Sources"    
        - ./build.py -b zed -p zynq --target source --ccache --ccache-clean --dl $CI_BR2_DL_DIR/zynq -q -l logs/${CI_BUILD_NAME}.log
        - cp -R $CI_BR2_DL_DIR/zynq $CI_BR2_DL_DIR/socfpga
        - cp -R $CI_BR2_DL_DIR/zynq $CI_BR2_DL_DIR/zynqmp

# Now get the custom source files
upload_logs_job:
    <<: *global_job_template
    stage: upload_logs
    when: always
    artifacts:
        paths:        
            - logs/
        expire_in: 1 month
    script:
        - echo "Capturing Pipeline logs"    

# Now get the custom source files
custom_sources_job:
    <<: *global_job_template
    stage: sources_custom
    script:
        - echo "Preparing Custom Sources"    
        - rm -rf $CI_BR2_DL_DIR/*/linux-*
        - rm -rf $CI_BR2_DL_DIR/*/uboot-*
        - rm -rf output/*/build
        - ./build.py -u -b zed -p zynq --target source --dl $CI_BR2_DL_DIR/zynq -l logs/${CI_BUILD_NAME}_zynq.log
        - ./build.py -u -b sockit -p socfpga --target source --dl $CI_BR2_DL_DIR/socfpga -l logs/${CI_BUILD_NAME}_socfpga.log
#        - ./build.py -u -b zcu102 -p zynqmp --target source --dl $CI_BR2_DL_DIR/zynqmp -l logs/${CI_BUILD_NAME}_zynqmp.log

########################
# Build Jobs (per-board)
########################

build_zed_job:
    <<: *build_job_template
    variables:
        CI_JOB_PLATFORM: zynq
        CI_JOB_BOARD: zed

build_sockit_job:
    <<: *build_job_template
    variables:
        CI_JOB_PLATFORM: socfpga
        CI_JOB_BOARD: sockit

