########################
# Global Config
########################

#cache:
#    key: "$CI_RUNNER_ID"
#    paths:
#        - dl/

variables:
    CONFIG_BR2_DL_DIR: "buildroot-ci/dl"
    GIT_STRATEGY: none

before_script:
    - export CONFIG_BR2_DL_DIR=$HOME/$CONFIG_BR2_DL_DIR
    - export

########################
# Job Templates
########################

# Global job template
# Used by all jobs
.global_job_template: &global_job_template
    script:
        - ./board/mathworks/common/scripts/gitlab_automation.sh    
    only:
        - /.*-ci$/
        - next
        - master
        - triggers
        - tags

# Global sysroot template
# Used by all sysroot jobs
.sysroot_job_template: &sysroot_job_template
    <<: *global_job_template  
    stage: sysroot
    artifacts:
        paths:
            - images/sysroot_$CONFIG_JOB_BOARD*.tar.bz
            - images/licenses_$CONFIG_JOB_BOARD*.txt
        expire_in: 2 days

# Global setup/teardown template
# Used by all setup/teardown jobs
.setup_job_template: &setup_job_template
    <<: *global_job_template  
    script:
        - '
            if [ "$CONFIG_SETUP_SCRIPT" != "" ]; then
                $CONFIG_SETUP_SCRIPT;
            fi
        '

# Global build job template
# Used by all build jobs
.build_job_template: &build_job_template
    <<: *global_job_template  
    stage: build
    artifacts:
        paths:
            - images/$CONFIG_JOB_BOARD*.zip
            - images/$CONFIG_JOB_BOARD*.gz
        expire_in: 2 days

# Global source job template
# Used by all source jobs
.build_job_template: &source_job_template
    <<: *global_job_template  
    stage: sources_custom
    

########################
# Pipeline Definition
########################

stages:
    - setup
    - sources_common
    - sources_custom
    - build
    - sysroot
    - upload_logs
    - teardown

########################
# Jobs
########################

# Prep and teardown jobs
setup:
    <<: *setup_job_template
    stage: setup

teardown:
    <<: *setup_job_template
    stage: teardown
    when: always

# Download the sources for all supported platforms
# Perform the download for one platform first, then copy the common bits
# To the others to save time
sources_common:
    <<: *global_job_template  
    stage: sources_common
    variables:
        GIT_STRATEGY: fetch

upload_logs:
    <<: *global_job_template
    stage: upload_logs
    when: always
    artifacts:
        paths:        
            - logs/
        expire_in: 2 weeks
    script:
        - echo "Capturing Pipeline logs"    

########################
# Source Jobs (per-platform)
########################

source_zynq:
    <<: *source_job_template
    variables:
        CONFIG_JOB_PLATFORM: zynq
        CONFIG_JOB_BOARD: zed

source_socfpga:
    <<: *source_job_template
    variables:
        CONFIG_JOB_PLATFORM: socfpga
        CONFIG_JOB_BOARD: sockit

source_zynqmp:
    <<: *source_job_template
    variables:
        CONFIG_JOB_PLATFORM: zynqmp
        CONFIG_JOB_BOARD: zcu102

########################
# Sysroot Jobs (per-platform)
########################

sysroot_zynq:
    <<: *sysroot_job_template
    variables:
        CONFIG_JOB_PLATFORM: zynq
        CONFIG_JOB_BOARD: zed

sysroot_socfpga:
    <<: *sysroot_job_template
    variables:
        CONFIG_JOB_PLATFORM: socfpga
        CONFIG_JOB_BOARD: sockit

sysroot_zynqmp:
    <<: *sysroot_job_template
    variables:
        CONFIG_JOB_PLATFORM: zynqmp
        CONFIG_JOB_BOARD: zcu102

########################
# Build Jobs (per-board)
########################

build_zed:
    <<: *build_job_template
    variables:
        CONFIG_JOB_PLATFORM: zynq
        CONFIG_JOB_BOARD: zed

build_zc706:
    <<: *build_job_template
    variables:
        CONFIG_JOB_PLATFORM: zynq
        CONFIG_JOB_BOARD: zc706

build_zc702:
    <<: *build_job_template
    variables:
        CONFIG_JOB_PLATFORM: zynq
        CONFIG_JOB_BOARD: zc702

build_sockit:
    <<: *build_job_template
    variables:
        CONFIG_JOB_PLATFORM: socfpga
        CONFIG_JOB_BOARD: sockit

build_alteracycv:
    <<: *build_job_template
    variables:
        CONFIG_JOB_PLATFORM: socfpga
        CONFIG_JOB_BOARD: alteracycv

build_zcu102:
    <<: *build_job_template
    variables:
        CONFIG_JOB_PLATFORM: zynqmp
        CONFIG_JOB_BOARD: zcu102

