########################
# Global Config
########################

#cache:
#    key: "$CI_RUNNER_ID"
#    paths:
#        - dl/

variables:
    CI_BR2_DL_DIR: "buildroot-ci/dl"
    GIT_STRATEGY: none

before_script:
    - export CI_BR2_DL_DIR=$HOME/$CI_BR2_DL_DIR
    - export

########################
# Job Templates
########################

# Global job template
# Used by all jobs
.global_job_template: &global_job_template
    script:
        - ./board/mathworks/common/scripts/gitlab_automation.sh    
    only:
        - /.*-ci$/
        - next
        - master
        - triggers
        - tags

# Global build job template
# Used by all build jobs
.build_job_template: &build_job_template
    <<: *global_job_template  
    stage: build
    artifacts:
        paths:
            - output/$CI_JOB_BOARD*/images/$CI_JOB_BOARD*.zip
            - output/$CI_JOB_BOARD*/images/$CI_JOB_BOARD*.gz
        expire_in: 1 month

# Global source job template
# Used by all source jobs
.build_job_template: &source_job_template
    <<: *global_job_template  
    stage: sources_custom
    

########################
# Pipeline Definition
########################

stages:
    - prep
    - sources_common
    - sources_custom
    - build
    - upload_logs

########################
# Jobs
########################

# Download the sources for all supported platforms
# Perform the download for one platform first, then copy the common bits
# To the others to save time
common_sources_job:
    <<: *global_job_template  
    stage: sources_common
    variables:
        GIT_STRATEGY: fetch

upload_logs_job:
    <<: *global_job_template
    stage: upload_logs
    when: always
    artifacts:
        paths:        
            - logs/
        expire_in: 1 month
    script:
        - echo "Capturing Pipeline logs"    

########################
# Source Jobs (per-platform)
########################

source_zynq_job:
    <<: *source_job_template
    variables:
        CI_JOB_PLATFORM: zynq
        CI_JOB_BOARD: zed

source_socfpga_job:
    <<: *source_job_template
    variables:
        CI_JOB_PLATFORM: socfpga
        CI_JOB_BOARD: sockit

source_zynqmp_job:
    <<: *source_job_template
    variables:
        CI_JOB_PLATFORM: zynqmp
        CI_JOB_BOARD: zcu102

########################
# Build Jobs (per-board)
########################

build_zed_job:
    <<: *build_job_template
    variables:
        CI_JOB_PLATFORM: zynq
        CI_JOB_BOARD: zed

build_sockit_job:
    <<: *build_job_template
    variables:
        CI_JOB_PLATFORM: socfpga
        CI_JOB_BOARD: sockit

build_zcu102_job:
    <<: *build_job_template
    variables:
        CI_JOB_PLATFORM: zynqmp
        CI_JOB_BOARD: zcu102

